# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Dévé
email: hi@timdeve.com
description: > # this means to ignore newlines until "baseurl:"
  Tim Dévé
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.timdeve.com" # the base hostname & protocol for your site
twitter_username: tim_deve
github_username:  timdeve

# Build settings
markdown: kramdown
sass:
  style: compressed
