# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Timothée Dévé
email: hi@timdeve.com
description: > # this means to ignore newlines until "baseurl:"
  This is my (Timothée "Tim" Dévé) personal website that contains
  my blog, my contact info and my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.timdeve.com" # the base hostname & protocol for your site
twitter_username: tim_deve
github_username:  timdeve

# Build settings
markdown: kramdown

# Navigation
navigation:
  - text: Home
    url: /
  - text: Blog
    url: /blog
  - text: Projects
    url: /projects
  - text: About Me
    url: /aboutme